
import { loadMetabolismConfig, saveMetabolismConfig } from './config.js';
import { searchArxiv, searchOpenAlex, downloadPaper } from '../tools/index.js';
import * as fs from 'fs/promises';
import * as path from 'path';

export async function runDailyHeartbeat(workdir: string): Promise<{ newPapers: number; newHypotheses: number }> {
  const config = await loadMetabolismConfig(workdir);
  
  if (!config) {
    throw new Error('Metabolism not initialized. Run /metabolism-init first.');
  }
  
  const today = new Date().toISOString().split('T')[0];
  
  if (config.lastRunDate === today) {
    console.log('Heartbeat already run today, skipping.');
    return { newPapers: 0, newHypotheses: 0 };
  }
  
  console.log(`Running daily heartbeat for day ${config.currentDay + 1}...`);
  
  await fs.mkdir(path.join(workdir, 'papers'), { recursive: true });
  await fs.mkdir(path.join(workdir, 'knowledge'), { recursive: true });
  await fs.mkdir(path.join(workdir, 'ideas'), { recursive: true });
  await fs.mkdir(path.join(workdir, 'logs'), { recursive: true });
  
  const fiveDaysAgo = new Date();
  fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);
  const dateFrom = fiveDaysAgo.toISOString().split('T')[0];
  
  let allPapers: any[] = [];
  
  if (config.sources.includes('arxiv')) {
    for (const keyword of config.keywords) {
      for (const category of config.arxivCategories) {
        const query = `${keyword} AND cat:${category}`;
        const result = await searchArxiv(query, 10);
        allPapers = [...allPapers, ...result.papers];
      }
    }
  }
  
  if (config.sources.includes('openalex')) {
    for (const keyword of config.keywords) {
      const result = await searchOpenAlex(keyword, 10);
      allPapers = [...allPapers, ...result.papers];
    }
  }
  
  const uniquePapers = allPapers.filter(paper => 
    paper.arxivId && !config.processedIds.includes(paper.arxivId)
  );
  
  console.log(`Found ${uniquePapers.length} new papers to process`);
  
  let downloadedCount = 0;
  for (const paper of uniquePapers) {
    const downloadPath = await downloadPaper(paper, path.join(workdir, 'papers'));
    if (downloadPath) {
      config.processedIds.push(paper.arxivId!);
      downloadedCount++;
      
      await processPaper(workdir, paper);
    }
  }
  
  const newHypotheses = await generateHypotheses(workdir, uniquePapers);
  
  config.currentDay += 1;
  config.lastRunDate = today;
  await saveMetabolismConfig(workdir, config);
  
  await writeLog(workdir, today, downloadedCount, newHypotheses.length);
  
  console.log(`Heartbeat completed: ${downloadedCount} new papers, ${newHypotheses.length} new hypotheses`);
  
  return {
    newPapers: downloadedCount,
    newHypotheses: newHypotheses.length
  };
}

async function processPaper(workdir: string, paper: any): Promise<void> {
  const notePath = path.join(workdir, 'knowledge', `paper_${paper.arxivId}.md`);
  
  const content = `# ${paper.title}

- **arXiv ID**: ${paper.arxivId}
- **Authors**: ${paper.authors.join(', ')}
- **Year**: ${paper.year || 'Unknown'}
- **URL**: ${paper.sourceUrl}

## Abstract
${paper.abstract || 'No abstract available'}

## Key Takeaways
[To be filled]
`;
  
  await fs.writeFile(notePath, content);
}

async function generateHypotheses(workdir: string, newPapers: any[]): Promise<any[]> {
  if (newPapers.length < 2) {
    return [];
  }
  
  const hypotheses: any[] = [];
  
  try {
    const hypothesisId = `hyp_${Date.now()}`;
    const hypothesisPath = path.join(workdir, 'ideas', `${hypothesisId}.md`);
    
    const content = `# Hypothesis ${hypothesisId}

## Hypothesis
Potential new research direction combining insights from recent papers.

## Reasoning
Based on analysis of ${newPapers.length} new papers published in the last 5 days.

## Source Papers
${newPapers.map(p => `- ${p.arxivId}: ${p.title}`).join('\n')}

## Evaluation
- Novelty: 3/5
- Feasibility: 3/5
- Impact: 3/5
`;
    
    await fs.writeFile(hypothesisPath, content);
    hypotheses.push({ id: hypothesisId });
  } catch (e) {
    console.error('Error generating hypothesis:', e);
  }
  
  return hypotheses;
}

async function writeLog(workdir: string, date: string, newPapers: number, newHypotheses: number): Promise<void> {
  const logPath = path.join(workdir, 'logs', `${date}.md`);
  
  const content = `# Metabolism Log - ${date}

## Summary
- New papers downloaded: ${newPapers}
- New hypotheses generated: ${newHypotheses}

## Details
[Auto-generated by heartbeat]
`;
  
  await fs.writeFile(logPath, content);
}
